"""O(1) suffix lookup from pre-computed hash-bucket data.

Mirrors the hs/ (existence) lookup pattern: 256 lazy-loaded Python modules
bucketed by the first 2 hex chars of the word's MD5 hash. Each bucket maps
the remaining 30-char hash to a pipe-joined suffix string.

Data generated by morphroot builder/build_wordnet_suffixes.py.

Related GitHub Issue (morphroot):
    #10 - Pre-compute WordNet suffix extraction for O(1) static lookup
    https://github.com/craigtrim/morphroot/issues/10
"""

from __future__ import annotations

import hashlib
import importlib

_cache: dict[str, dict[str, str]] = {}


def _calculate_md5(word: str) -> str:
    return hashlib.md5(word.lower().strip().encode()).hexdigest()


def _get_bucket(prefix: str) -> dict[str, str]:
    if prefix not in _cache:
        module = importlib.import_module(f'wordnet_lookup.sx.sx_{prefix}')
        _cache[prefix] = getattr(module, f'suffixes_{prefix}')
    return _cache[prefix]


def get_suffixes(word: str) -> list[str] | None:
    """Return the morphological suffixes for a WordNet word.

    Args:
        word: Any English word. Case-insensitive.

    Returns:
        List of suffixes in derivation order (innermost first) if the word
        is in WordNet and has derivational suffixes, e.g. ["ful", "ly"].
        Empty list [] if the word is in WordNet but is monomorphemic.
        None if the word is not in WordNet at all.

    Examples:
        >>> get_suffixes("happiness")
        ['ness']
        >>> get_suffixes("beautifully")
        ['ful', 'ly']
        >>> get_suffixes("cat")
        []
        >>> get_suffixes("xyz123")
        None
    """
    from .find_wordnet import FindWordnet

    normalized = word.lower().strip()
    if not normalized:
        return None

    h = _calculate_md5(normalized)
    value = _get_bucket(h[:2]).get(h[2:])

    if value is not None:
        return value.split('|')

    if FindWordnet().exists(normalized):
        return []

    return None
